#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

triangleNumbers = []
pentagonalNumbers = []
hexagonalNumbers = []

notFound = True
startTn = 286
startPn = 166
startHn = 144

while notFound:
    triangleNumbers.append(int((startTn*(startTn + 1))/2))
    pentagonalNumbers.append(int( startPn*((3*startPn) -1) / 2))
    hexagonalNumbers.append(int( startHn*((2*startHn) - 1)))
    x = triangleNumbers[(startTn - 286)]
    if( ( x in pentagonalNumbers) and (x in hexagonalNumbers)):
        notFound = False
    else: 
        startTn += 1
        startPn += 1
        startHn += 1
print(triangleNumbers[startTn - 286])
