#!/usr/bin/perl

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

use strict;
use warnings;

my ($flag, $i, $j, $k) = (0, 0, 0);

for( $i = 1; $flag == 0; $i++ )
{
    $j += $i;
    if( noOfDivisors($j) >= 5000 )
    {
	$flag = 1;
    }
}

print "$j\n";

sub noOfDivisors
{
    my ($i, $noOfDivisors, $j) = (shift, 1);

    for( $j = 2; $j <= $i/2; $j++ )
    {
	$noOfDivisors++	if( ($i % $j) == 0 );
    }

    return $noOfDivisors;
}
