#!/usr/bin/env python3
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

pentagonalNumbers = []
hexagonalNumbers = []

notFound = True
startPn = 166
startHn = 144

while notFound:
    pentagonalNumbers.append(int( startPn*((3*startPn) -1) / 2))
    hexagonalNumbers.append(int( startHn*((2*startHn) - 1)))
    x = pentagonalNumbers[(startPn - 166)]
    if( ( x in hexagonalNumbers)) :
        notFound = False
    else: 
        startPn += 1
        startHn += 1
print(pentagonalNumbers[startPn - 166]) 
